language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "nightly" # 3.7-dev
install: 
  - pip install -r requirements.txt
  - pip install codecov
script:
  - ./test.sh
after_success:
  - codecov